# Generated by Django 4.2.7 on 2023-11-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='number',
            field=models.CharField(help_text='Введите номер машины', max_length=8, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='INN',
            field=models.DecimalField(decimal_places=0, help_text='Введите ИНН', max_digits=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='cars',
            field=models.ForeignKey(help_text='Введите автомобиль', on_delete=django.db.models.deletion.CASCADE, to='catalog.cars', verbose_name='Автомобили'),
        ),
    ]
