# Generated by Django 4.2.7 on 2023-11-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_cars_number_alter_drivers_inn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['mark']},
        ),
        migrations.AlterModelOptions(
            name='drivers',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='cars',
            name='number',
            field=models.CharField(db_index=True, help_text='Введите номер машины', max_length=9, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='INN',
            field=models.DecimalField(db_index=True, decimal_places=0, help_text='Введите ИНН', max_digits=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='cars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cars', verbose_name='Автомобили'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_from',
            field=models.TextField(help_text='Введите адрес подачи такси', verbose_name='Адрес подачи'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_to',
            field=models.TextField(help_text='Введите адрес следования', verbose_name='Адрес следования'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(db_index=True, help_text='Введите дату и время заказа', verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='drivers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.drivers', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='Введите длину маршрута в километрах', max_digits=6, verbose_name='Длина маршрута'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number_of_passengers',
            field=models.DecimalField(decimal_places=0, help_text='Введите количество пассажиров', max_digits=1, verbose_name='Количество пассажиров'),
        ),
    ]
